defmodule Pristine.Manifest.Endpoint do
  @moduledoc """
  Endpoint definition extracted from a manifest.
  """

  defstruct id: nil,
            method: nil,
            path: nil,
            description: nil,
            resource: nil,
            request: nil,
            response: nil,
            async: false,
            poll_endpoint: nil,
            timeout: nil,
            retry: nil,
            telemetry: nil,
            streaming: false,
            headers: %{},
            query: %{},
            body_type: nil,
            content_type: nil,
            auth: nil,
            circuit_breaker: nil,
            rate_limit: nil,
            idempotency: false,
            idempotency_header: nil,
            stream_format: nil,
            event_types: nil,
            deprecated: false,
            tags: nil,
            error_types: nil,
            response_unwrap: nil

  @type t :: %__MODULE__{
          id: String.t(),
          method: String.t(),
          path: String.t(),
          description: String.t() | nil,
          resource: String.t() | nil,
          request: String.t() | nil,
          response: String.t() | nil,
          async: boolean(),
          poll_endpoint: String.t() | nil,
          timeout: non_neg_integer() | nil,
          retry: String.t() | nil,
          telemetry: String.t() | nil,
          streaming: boolean(),
          headers: map(),
          query: map(),
          body_type: String.t() | nil,
          content_type: String.t() | nil,
          auth: String.t() | nil,
          circuit_breaker: String.t() | nil,
          rate_limit: String.t() | nil,
          idempotency: boolean(),
          idempotency_header: String.t() | nil,
          stream_format: String.t() | nil,
          event_types: [String.t()] | nil,
          deprecated: boolean(),
          tags: [String.t()] | nil,
          error_types: list() | nil,
          response_unwrap: String.t() | nil
        }
end
