defmodule Pristine.Core.Context do
  @moduledoc """
  Internal runtime context for executing request specs.

  `Pristine.Client` is the public runtime client contract.
  """

  defstruct config: nil,
            base_url: nil,
            pool_base: nil,
            headers: %{},
            auth: [],
            transport: nil,
            transport_opts: [],
            stream_transport: nil,
            streaming: nil,
            serializer: nil,
            multipart: nil,
            multipart_opts: [],
            default_query: %{},
            default_timeout: nil,
            transform_opts: [],
            retry: nil,
            retry_opts: [],
            result_classifier: nil,
            admission_control: nil,
            admission_opts: [],
            rate_limiter: nil,
            rate_limit_opts: [],
            circuit_breaker: nil,
            circuit_breaker_opts: [],
            telemetry: nil,
            telemetry_events: %{},
            telemetry_metadata: %{},
            semaphore: nil,
            retry_policies: %{},
            type_schemas: %{},
            idempotency_header: "X-Idempotency-Key",
            query_opts: [],
            pool_manager: nil,
            package_version: nil,
            error_module: nil,
            response_wrapper: nil,
            logger: nil,
            log_level: nil,
            dump_headers?: false,
            redact_headers: nil,
            extra_headers: nil

  @type t :: %__MODULE__{
          config: term() | nil,
          base_url: String.t() | nil,
          pool_base: term() | nil,
          headers: map(),
          auth: list(),
          transport: module() | nil,
          transport_opts: keyword(),
          stream_transport: module() | nil,
          streaming: module() | nil,
          serializer: module() | nil,
          multipart: module() | nil,
          multipart_opts: keyword(),
          default_query: map(),
          default_timeout: non_neg_integer() | nil,
          transform_opts: keyword(),
          retry: module() | nil,
          retry_opts: keyword(),
          result_classifier: module() | function() | nil,
          admission_control: module() | nil,
          admission_opts: keyword(),
          rate_limiter: module() | nil,
          rate_limit_opts: keyword(),
          circuit_breaker: module() | nil,
          circuit_breaker_opts: keyword(),
          telemetry: module() | nil,
          telemetry_events: map(),
          telemetry_metadata: map(),
          semaphore: module() | nil,
          retry_policies: map(),
          type_schemas: map(),
          idempotency_header: String.t(),
          query_opts: keyword(),
          pool_manager: module() | nil,
          package_version: String.t() | nil,
          error_module: module() | nil,
          response_wrapper: module() | nil,
          logger: (atom(), String.t(), map() -> term()) | nil,
          log_level: :debug | :info | :warn | :error | nil,
          dump_headers?: boolean(),
          redact_headers: function() | nil,
          extra_headers: function() | nil
        }

  @spec new(keyword()) :: t()
  def new(opts \\ []) do
    %__MODULE__{
      config: Keyword.get(opts, :config),
      base_url: Keyword.get(opts, :base_url),
      pool_base: Keyword.get(opts, :pool_base),
      headers: Keyword.get(opts, :headers, %{}),
      auth: Keyword.get(opts, :auth, []),
      transport: Keyword.get(opts, :transport),
      transport_opts: Keyword.get(opts, :transport_opts, []),
      stream_transport: Keyword.get(opts, :stream_transport),
      streaming: Keyword.get(opts, :streaming),
      serializer: Keyword.get(opts, :serializer),
      multipart: Keyword.get(opts, :multipart, Pristine.Adapters.Multipart.Ex),
      multipart_opts: Keyword.get(opts, :multipart_opts, []),
      default_query: Keyword.get(opts, :default_query, %{}),
      default_timeout: Keyword.get(opts, :default_timeout),
      transform_opts: Keyword.get(opts, :transform_opts, []),
      retry: Keyword.get(opts, :retry),
      retry_opts: Keyword.get(opts, :retry_opts, []),
      result_classifier:
        Keyword.get(opts, :result_classifier, Pristine.Adapters.ResultClassifier.HTTP),
      admission_control:
        Keyword.get(opts, :admission_control, Pristine.Adapters.AdmissionControl.Noop),
      admission_opts: Keyword.get(opts, :admission_opts, []),
      rate_limiter: Keyword.get(opts, :rate_limiter),
      rate_limit_opts: Keyword.get(opts, :rate_limit_opts, []),
      circuit_breaker: Keyword.get(opts, :circuit_breaker),
      circuit_breaker_opts: Keyword.get(opts, :circuit_breaker_opts, []),
      telemetry: Keyword.get(opts, :telemetry),
      telemetry_events: Keyword.get(opts, :telemetry_events, %{}),
      telemetry_metadata: Keyword.get(opts, :telemetry_metadata, %{}),
      semaphore: Keyword.get(opts, :semaphore),
      retry_policies: Keyword.get(opts, :retry_policies, %{}),
      type_schemas: Keyword.get(opts, :type_schemas, %{}),
      idempotency_header: Keyword.get(opts, :idempotency_header, "X-Idempotency-Key"),
      query_opts: Keyword.get(opts, :query_opts, []),
      pool_manager: Keyword.get(opts, :pool_manager),
      package_version: Keyword.get(opts, :package_version),
      error_module: Keyword.get(opts, :error_module),
      response_wrapper: Keyword.get(opts, :response_wrapper),
      logger: Keyword.get(opts, :logger),
      log_level: Keyword.get(opts, :log_level),
      dump_headers?: Keyword.get(opts, :dump_headers?, false),
      redact_headers: Keyword.get(opts, :redact_headers),
      extra_headers: Keyword.get(opts, :extra_headers)
    }
  end
end
